# Generated by Django 5.2.4 on 2025-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("name", "level")},
        ),
        migrations.AddField(
            model_name="cv",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="cv_skills",
                to="main.skill",
                verbose_name="Skills",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Skill Name"
            ),
        ),
        migrations.RemoveField(
            model_name="skill",
            name="cv",
        ),
    ]
