# Generated by Django 5.2.4 on 2025-07-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_skill_unique_together_cv_skills_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
    ]
