# Generated by Django 5.2.4 on 2025-07-23 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=10)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("method", models.CharField(db_index=True, max_length=10)),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("query_string", models.TextField(blank=True)),
                ("remote_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "response_time_ms",
                    models.FloatField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("content_length", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "method"],
                        name="audit_reque_timesta_d6c316_idx",
                    ),
                    models.Index(
                        fields=["path", "timestamp"], name="audit_reque_path_260cdb_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_reque_user_id_0634d8_idx",
                    ),
                ],
            },
        ),
    ]
